services:
  os:
    build: .
    command: ["/usr/bin/sshd", "-D"]
    ports:
      - 22:22/tcp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  kcptun-ssh:
    image: xtaci/kcptun 
    command: ["server", "-l", ":22", "-t", "os:22"]
    ports:
      - 22:22/udp
    depends_on:
      - os
